#!/usr/bin/env python3
"""Assert docs/info.md's ring predictions match a fresh computation. Defect M21.

WHY THIS EXISTS. `docs/info.md` publishes, per PVT corner, what each ring
should do in silicon -- the numbers a person holds the first chip against in
2027, with no way to re-derive them once the die is in hand. They were
regenerated BY HAND, last at 5ded3aa, and `flow/ring_prediction.py` appears
nowhere in .github/workflows. So they silently aged out: the committed table
says it came from run 30934157150 on lib-v1.4, and since then lib-v1.5
surfaced and repaired 22 max-fanout violations, lib-v1.6's measured hold
constraint took the shipped build to 63 hold buffers at 56.2% utilization
against that run's 53.4%, and M20 moved the floorplan.

Ring period is set by the ROUTED result -- the whole lesson of H3 and M7 -- so
a table computed from a different routed netlist is not a prediction about this
chip. Every other claim this repo makes is asserted on every run. This one was
not, which is why it drifted; a number nobody recomputes is a number that
drifts.

WHAT IT COMPARES. Both published tables, against `ring_prediction.silicon()`
run on the same artifact the badge is about:
  * the headline table  -- `nom` extraction, self-consistent MHz and count
  * the RC band table   -- `min` and `max` counts per PVT
A tolerance is allowed because the doc rounds; it is stated, not implicit.

⚠️ IT MUST NOT PASS WHEN IT CANNOT SEE. Both sides are asserted non-empty and
the two sides are asserted to cover the same (corner, ring) set, because "no
rows parsed" and "no disagreement" are the same output otherwise -- which is
the defect class this repo keeps finding, and M21 itself is an instance.
"""

import argparse
import ast
import io
import re
import sys
from contextlib import redirect_stdout
from pathlib import Path

# This runs on a Windows dev box as well as in CI, where stdout defaults to
# cp1252: any non-ASCII reporting character raises UnicodeEncodeError, so the
# script would crash WHILE PRINTING its own finding -- doing the work and then
# losing the answer, which is the one outcome a checker must never have.
# Output is kept ASCII; this reconfigure is belt-and-braces for future edits.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ring_prediction

ROOT = Path(__file__).resolve().parents[1]
RINGS = ("INV", "NAND2", "NOR2")
PVTS = ("ff", "tt", "ss")

# "nom_tt_025C_1v80   (lib own_hardening_tt_025C_1v80.lib, spef nom)"
CORNER = re.compile(r"^(\w+)_(\w+_\w+_\w+)\s+\(lib ", re.M)
# "  INV      731.8M    740.1M    735.0M          620.6M          397"
ROW = re.compile(
    r"^\s+(INV|NAND2|NOR2)\s+([\d.]+)M\s+([\d.]+)M\s+([\d.]+)M\s+([\d.]+)M\s+(\d+)\s*$",
    re.M)
# "| INV | 731.8 MHz / 468 | **620.6 MHz / 397** | 457.8 MHz / 293 |"
DOC_MAIN = re.compile(
    r"^\|\s*(INV|NAND2|NOR2)\s*\|(.+)\|\s*$", re.M)
CELL_MHZ = re.compile(r"([\d.]+)\s*MHz\s*/\s*(\d+)")
CELL_BAND = re.compile(r"(\d+)\s*\.\.\s*(\d+)")


def computed(run_dir):
    """-> {(rc, pvt_short, ring): (mhz, count)} from a fresh run."""
    buf = io.StringIO()
    with redirect_stdout(buf):
        ring_prediction.silicon(run_dir)
    text = buf.getvalue()
    out, marks = {}, list(CORNER.finditer(text))
    if not marks:
        sys.exit(f"ERROR: ring_prediction.silicon('{run_dir}') printed no "
                 f"corner headers. Refusing to report agreement with a "
                 f"computation that did not happen.")
    for i, m in enumerate(marks):
        rc, pvt = m.group(1), m.group(2)
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        for r in ROW.finditer(text[m.end():end]):
            out[(rc, pvt.split("_")[0], r.group(1))] = (float(r.group(5)),
                                                        int(r.group(6)))
    if not out:
        sys.exit("ERROR: corner headers were found but no ring rows parsed — "
                 "ring_prediction.py's output format changed and this check "
                 "would silently compare nothing.")
    return out, text


def doc_tables():
    """-> (main{(pvt,ring):(mhz,count)}, band{(pvt,ring):(min,max)})."""
    md = (ROOT / "docs" / "info.md").read_text(encoding="utf-8")
    main, band = {}, {}
    for m in DOC_MAIN.finditer(md):
        ring, rest = m.group(1), m.group(2)
        cells = [c.strip() for c in rest.split("|")]
        mhz = [CELL_MHZ.search(c) for c in cells]
        if all(mhz) and len(mhz) == len(PVTS):
            for pvt, g in zip(PVTS, mhz):
                main[(pvt, ring)] = (float(g.group(1)), int(g.group(2)))
            continue
        bands = [CELL_BAND.search(c) for c in cells]
        if all(bands) and len(bands) == len(PVTS):
            for pvt, g in zip(PVTS, bands):
                band[(pvt, ring)] = (int(g.group(1)), int(g.group(2)))
    return main, band


def resolve_run(path: str) -> Path:
    """Accept either a run directory or the `runs/` parent holding one.

    The step in gds.yaml passes `runs`, because the run's directory NAME is the
    flow's business, not ours -- every other check in that workflow globs for
    it rather than spelling it, and hardcoding `runs/wokwi` would break
    silently the day the name changes. Fails loudly when nothing matches: this
    asserts a property of a BUILT design and must not pass when there is none.
    """
    p = Path(path)
    if (p / "final" / "sdf").is_dir():
        return p
    cands = [d for d in p.iterdir()
             if d.is_dir() and (d / "final" / "sdf").is_dir()] if p.is_dir() else []
    if not cands:
        sys.exit(f"ERROR: no run with final/sdf under '{path}'. This check "
                 f"asserts that a published table matches a BUILT design; "
                 f"there is no design here to match it against.")
    return max(cands, key=lambda d: d.stat().st_mtime)


# "| tt (25 C, 1.80 V) | **25.67 ps** | **35.30 ps** | **55.71 ps** |"
DOC_TP = re.compile(r"^\|\s*(ff|tt|ss)\s*\([^)]*\)\s*\|(.+)\|\s*$", re.M)
PS = re.compile(r"([\d.]+)\s*ps")

BRINGUP = ROOT / "bringup" / "vslice_bringup.py"
SDC = ROOT / "harden" / "signoff.sdc"


def doc_tp_table():
    """-> {(pvt, ring): ps} from the published CELL-DELAY table.

    Added 2026-08-21 together with the INV de-blend. It is a SECOND published
    prediction in the same file, so it gets the same treatment as the first:
    left unasserted it would have re-created M21 inside the fix for M21.
    """
    md = (ROOT / "docs" / "info.md").read_text(encoding="utf-8")
    out = {}
    for m in DOC_TP.finditer(md):
        vals = PS.findall(m.group(2))
        if len(vals) == len(RINGS):
            for ring, v in zip(RINGS, vals):
                out[(m.group(1), ring)] = float(v)
    return out


def sdc_ro_periods():
    """-> {pvt_short: period_ns} from harden/signoff.sdc's ro_period_by_pvt.

    THE FOURTH DESCENDANT OF THE RING COMPUTATION, AND THE ONLY ONE THAT WAS
    NEVER ASSERTED. docs/info.md's three tables and the bring-up script's two
    constants are checked above; this table was not, and it has now gone stale
    TWICE -- M14 (computed pre-M7, over-constraining by 35-47%) and M32
    (transcribed on lib-v1.4, demanding 2.166 ns of an ss ring that runs at
    3.116). Both times the fix landed as a regeneration and not as a check,
    which is how it came back.

    It matters more than a datasheet number, because this one is an INPUT to
    signoff rather than an output. Too fast and the prescaler is timed against
    a ring the die will never present, producing phantom setup violations that
    get "fixed" with margin. Too slow and the counter signs off with headroom
    it does not have, drops edges on silicon, and returns a LOW count -- which
    reads as a slower cell than predicted, a perfectly plausible result that
    is wrong.
    """
    txt = SDC.read_text(encoding="utf-8")
    m = re.search(r"array set ro_period_by_pvt \{(.*?)\}", txt, re.S)
    if not m:
        sys.exit("ERROR: harden/signoff.sdc no longer defines "
                 "ro_period_by_pvt. This check must not silently stop "
                 "covering the constraint it was written for.")
    out = {}
    for line in m.group(1).splitlines():
        f = line.split()
        if len(f) == 2:
            out[f[0].split("_")[0]] = float(f[1])
    return out


def bringup_constants():
    """-> (PREDICTED_HZ, PREDICTED_BAND_HZ) parsed from the bring-up script.

    THE FILE M21's FIRST FIX DID NOT REACH. This checker was written to stop
    docs/info.md going stale and pointed only at docs/info.md, while the script
    that actually runs on the demo board -- the one artifact a human touches in
    2027 -- kept a two-library-generation-old prediction behind a comment
    reading "Keep them in sync". A human instruction is the mechanism, not the
    fix, and both review gates found it independently.

    Parsed with `ast`, not imported: importing runs module-level code, and a
    bring-up script is not something a CI check should execute.
    """
    tree = ast.parse(BRINGUP.read_text(encoding="utf-8"))
    found = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            t = node.targets[0]
            if isinstance(t, ast.Name) and t.id in ("PREDICTED_HZ",
                                                    "PREDICTED_BAND_HZ"):
                found[t.id] = ast.literal_eval(node.value)
    missing = {"PREDICTED_HZ", "PREDICTED_BAND_HZ"} - set(found)
    if missing:
        sys.exit(f"ERROR: {BRINGUP.name} no longer defines {sorted(missing)} "
                 f"at module level. This check must not silently stop covering "
                 f"the file it was extended to cover.")
    return found["PREDICTED_HZ"], found["PREDICTED_BAND_HZ"]


def tp_from(got, pvt):
    """Cell delays implied by the fresh nom-corner ring predictions, in ps.

    The INV ring is 30 INV_X1 + 1 NAND2_X1 (an odd-stage ring needs its enable
    gate somewhere), so its period is 2*(30*tp_INV + tp_NAND2) and dividing by
    2*31 returns a 30:1 BLEND -- the defect this table exists to correct.
    De-blend with the NAND2 ring, which measures that stage directly.
    """
    f = {r: got[("nom", pvt, r)][0] * 1e6 for r in RINGS}
    return {"INV": (1 / f["INV"] - 1 / (31 * f["NAND2"])) / 60 * 1e12,
            "NAND2": 1 / (2 * 31 * f["NAND2"]) * 1e12,
            "NOR2": 1 / (2 * 31 * f["NOR2"]) * 1e12}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("run")
    ap.add_argument("--mhz-tol", type=float, default=0.15,
                    help="MHz, absolute; the doc prints one decimal")
    ap.add_argument("--count-tol", type=int, default=1,
                    help="counts, absolute; the doc prints an integer")
    ap.add_argument("--sdc-tol", type=float, default=0.005,
                    help="ns of slack allowed on signoff.sdc's ro_clk period")
    ap.add_argument("--tp-tol", type=float, default=0.02,
                    help="ps, absolute; the doc prints two decimals")
    args = ap.parse_args()

    run = resolve_run(args.run)
    got, raw = computed(str(run))
    main_t, band_t = doc_tables()
    if len(main_t) != len(RINGS) * len(PVTS):
        sys.exit(f"ERROR: parsed {len(main_t)} headline cells from "
                 f"docs/info.md, expected {len(RINGS) * len(PVTS)}. The "
                 f"published table's shape changed; this check would compare "
                 f"a subset and call it agreement.")
    if len(band_t) != len(RINGS) * len(PVTS):
        sys.exit(f"ERROR: parsed {len(band_t)} RC-band cells from "
                 f"docs/info.md, expected {len(RINGS) * len(PVTS)}.")

    bad = []
    for (pvt, ring), (mhz, cnt) in sorted(main_t.items()):
        key = ("nom", pvt, ring)
        if key not in got:
            bad.append(f"  {pvt}/{ring}: the doc publishes it, the fresh "
                       f"computation has no nom row for it")
            continue
        g_mhz, g_cnt = got[key]
        if abs(g_mhz - mhz) > args.mhz_tol or abs(g_cnt - cnt) > args.count_tol:
            bad.append(f"  {pvt:>3s}/{ring:<6s} headline: doc {mhz:7.1f} MHz / "
                       f"{cnt:4d}   fresh {g_mhz:7.1f} MHz / {g_cnt:4d}")
    for (pvt, ring), (lo, hi) in sorted(band_t.items()):
        for rc, want in (("min", lo), ("max", hi)):
            key = (rc, pvt, ring)
            if key not in got:
                bad.append(f"  {pvt}/{ring}: no {rc} row in the fresh "
                           f"computation")
                continue
            if abs(got[key][1] - want) > args.count_tol:
                bad.append(f"  {pvt:>3s}/{ring:<6s} {rc} band: doc {want:4d}"
                           f"   fresh {got[key][1]:4d}")

    # Name the RESOLVED run, not the argument: a log that says "runs" does not
    # tell the next reader which build the published table was checked against.
    tp_t = doc_tp_table()
    if len(tp_t) != len(RINGS) * len(PVTS):
        sys.exit(f"ERROR: parsed {len(tp_t)} cell-delay cells from "
                 f"docs/info.md, expected {len(RINGS) * len(PVTS)}. The "
                 f"published cell-delay table's shape changed.")
    for pvt in PVTS:
        fresh_tp = tp_from(got, pvt)
        for ring in RINGS:
            doc_ps = tp_t[(pvt, ring)]
            if abs(fresh_tp[ring] - doc_ps) > args.tp_tol:
                bad.append(f"  {pvt:>3s}/{ring:<6s} cell delay: doc "
                           f"{doc_ps:6.2f} ps   fresh {fresh_tp[ring]:6.2f} ps")

    # The SDC's ring period must be the FASTEST ring at that PVT over every RC
    # variant -- which is what the file's own comment says it is.
    sdc = sdc_ro_periods()
    if set(sdc) != set(PVTS):
        sys.exit(f"ERROR: signoff.sdc covers {sorted(sdc)}, expected "
                 f"{sorted(PVTS)}")
    for pvt in PVTS:
        fastest = max(got[(rc, pvt, ring)][0]
                      for rc in ("min", "nom", "max") for ring in RINGS)
        want = 1e3 / fastest
        if abs(sdc[pvt] - want) > args.sdc_tol:
            bad.append(f"  {pvt:>3s}       signoff.sdc ro_clk: file "
                       f"{sdc[pvt]:.3f} ns   fresh {want:.3f} ns "
                       f"({fastest:.1f} MHz, the fastest ring over min/nom/max RC)")

    pred_hz, band_hz = bringup_constants()
    if set(pred_hz) != set(RINGS) or set(band_hz) != set(RINGS):
        sys.exit(f"ERROR: the bring-up script's tables cover {sorted(pred_hz)} "
                 f"/ {sorted(band_hz)}, expected {sorted(RINGS)} in both.")
    for ring in RINGS:
        want = got[("nom", "tt", ring)][0]
        if abs(pred_hz[ring] / 1e6 - want) > args.mhz_tol:
            bad.append(f"  bringup PREDICTED_HZ[{ring}]: script "
                       f"{pred_hz[ring]/1e6:7.1f} MHz   fresh {want:7.1f} MHz")
        lo_want, hi_want = got[("nom", "ss", ring)][0], got[("nom", "ff", ring)][0]
        lo, hi = band_hz[ring][0] / 1e6, band_hz[ring][1] / 1e6
        if abs(lo - lo_want) > args.mhz_tol or abs(hi - hi_want) > args.mhz_tol:
            bad.append(f"  bringup PREDICTED_BAND_HZ[{ring}]: script "
                       f"{lo:7.1f}..{hi:7.1f}   fresh "
                       f"{lo_want:7.1f}..{hi_want:7.1f} MHz")

    print(f"compared {len(main_t)} headline + {2 * len(band_t)} band + "
          f"{len(tp_t)} cell-delay numbers against a fresh computation on "
          f"{run}, plus {3 * len(RINGS)} constants in {BRINGUP.name}")
    if bad:
        print("\nPUBLISHED PREDICTIONS DISAGREE WITH THE SHIPPED DESIGN — defect M21:")
        print("\n".join(bad))
        print("\nRegenerate with `python flow/ring_prediction.py --run "
              "<run-dir>` and update docs/info.md, INCLUDING the run id and "
              "library tag in the sentence above the table.")
        print("\n⛔ Do not widen the tolerance to make this pass. These are the "
              "numbers the first silicon gets judged against; if they moved, "
              "the published prediction moved.")
        return 1
    print("PASS: the published ring predictions match this design.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
